# Generated by Django 4.1 on 2022-10-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_categories_name_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
